config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/cessda/cessda.cdc.osmh-indexer.cmm:
      branch: main
      repo: https://github.com/cessda/cessda.cdc.osmh-indexer.cmm.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/cessda/cessda.cdc.osmh-indexer.cmm git:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-silver-spoonbill.sh
        container: qc.acc_crappy-cerulean-angora
  QC.Doc:
    repos:
      github.com/cessda/cessda.cdc.osmh-indexer.cmm find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-sapphire-saola.sh
        container: qc.doc_sickly-harlequin-binturong
      github.com/cessda/cessda.cdc.osmh-indexer.cmm git:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-sangria-bandicoot.sh
        container: qc.doc_leaky-plum-dog
      github.com/cessda/cessda.cdc.osmh-indexer.cmm markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-myrtle-hare.sh
        container: qc.doc_silly-harlequin-fowl
  QC.Lic:
    repos:
      github.com/cessda/cessda.cdc.osmh-indexer.cmm licensee:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-lavender-akita.sh
        container: qc.lic_wiggy-buff-echidna
  QC.Met:
    repos:
      github.com/cessda/cessda.cdc.osmh-indexer.cmm cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-cerulean-yak.sh
        container: qc.met_skimpy-magnolia-chimpanzee
  QC.Sty:
    repos:
      github.com/cessda/cessda.cdc.osmh-indexer.cmm checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.homely-dandelion-dodo.sh
        container: qc.sty_scummy-saffron-retriever
      github.com/cessda/cessda.cdc.osmh-indexer.cmm hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-amber-kingfisher.sh
        container: qc.sty_woozy-bronze-spider
      github.com/cessda/cessda.cdc.osmh-indexer.cmm jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-eggplant-oriole.sh
        container: qc.sty_messy-emerald-capuchin
  QC.Ver:
    repos:
      github.com/cessda/cessda.cdc.osmh-indexer.cmm get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-thistle-badger.sh
        container: qc.ver_skimpy-fuchsia-dane
timeout: 5400
